### ISSUE TITLE
Upload direct export of current test cases in BSCW

### ISSUE THREAD

**Issue by RagingKore** [DEXPI/TestCases#1]

**Comment by michaelwiedau** [comment]
Currently trying to do so. GitHub Desktop version has internet-problems on my machine...

**Comment by RagingKore** [comment]
I don't believe is your machine. It's this network.

**Comment by michaelwiedau** [comment]
I suppose it is the Evonik-VPN SSH Restriction. I am not allowed to do SSH with my Evonik machine.

**Comment by michaelwiedau** [comment]
Just a test comment
