### ISSUE TITLE
More Ixx Test Cases

### ISSUE THREAD

**Issue by sommersohn** [DEXPI/TestCases#11]
We need more Instrumentation Test cases. 
Add new Test Cases for different representations / possibilities. 
1. Prepare an overview (PS)
2. Create Folders (PS)
3. Add PPTXs (PS)
4. Provide Outputs (all)

**Comment by PaulSnijder** [comment]
4 new test cases created, with folder and PPTX: I09 - I12
Intergraph export files added and verificator results added to case I02, I04, I11 and I12
